name: audio_diaries_flutter
description: Audio Diaries Flutter is a mobile application that allows users to record audio diaries and store them locally and in a cloud database. The application is built using Flutter and Dart, and uses Firebase for cloud storage.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.7.0+18

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  app_settings: ^5.0.0

  table_calendar: ^3.0.9
  #Adaptive font
  flutter_screenutil: ^5.8.4

  #Formating
  intl: ^0.19.0

  #firebase
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0

  permission_handler: ^11.3.0

  #Audio recording & playback
  flutter_sound: ^9.2.13
  audio_session: ^0.1.16
  audioplayers: ^6.1.0

  #internal storage
  path_provider: ^2.1.0

  #Http
  http: 

  #path manipulation
  path: ^1.8.3

  #state management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  #Data
  shared_preferences: ^2.2.0

  #Database
  objectbox: ^4.0.2
  objectbox_flutter_libs: any


  #Animations
  rive: ^0.13.14

  #Amplify
  amplify_flutter: ^2.4.1
  amplify_auth_cognito: ^2.4.1
  amplify_storage_s3: ^2.4.1
  amplify_datastore: ^2.4.1
  amplify_api: ^2.4.1

  #Notification
  awesome_notifications: ^0.10.0

  #URL Launcher
  url_launcher: ^6.1.14

  #Web
  webview_flutter: ^4.10.0

  #Pendo
  pendo_sdk: ^3.4.1

  #Splash
  flutter_native_splash: ^2.3.4

  #Misc
  dotted_border: ^2.1.0
  flutter_secure_storage: ^9.2.1
  wakelock_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #Database
  build_runner: ^2.0.0
  objectbox_generator: any

  #Icon
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^5.0.0


#Icon Configuration
flutter_launcher_icons:
  image_path: "assets/images/logo_white.png"
  ios: true
  android: true
  min_sdk_android: 24

#Splash Configuration
flutter_native_splash:
  color: "#5B89FF"
  color_dark: "#5B89FF"
  image: "assets/images/logo_white.png"
  android: true
  ios: true
  web: false

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/animations/onboarding/
    - assets/animations/recording/
    - assets/protocol.json
    - assets/onboarding.json

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
